. Effect of Number of Trees
Dataset: Heart Disease Dataset
Download:

https://www.kaggle.com/datasets/johnsmith88/heart-disease-dataset

Tasks

Train Random Forest with:
10 trees

50 trees

100 trees

200 trees

Create a comparison table of:
Number of Trees

Train Accuracy

Test Accuracy

Training Time


Which number of trees gives the best balance between
performance and computation?

In [10]:
import pandas as pd
import time

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [11]:
#load dataset
df = pd.read_csv("heart.csv")

df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [12]:
#Separate Features and TargetX = df.drop('target',axis=1)

X = df.drop('target',axis=1)
y = df['target']

print(X.head())
print(y.head)

   age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2
1   53    1   0       140   203    1        0      155      1      3.1      0
2   70    1   0       145   174    0        1      125      1      2.6      0
3   61    1   0       148   203    0        1      161      0      0.0      2
4   62    0   0       138   294    1        1      106      0      1.9      1

   ca  thal
0   2     3
1   0     3
2   0     3
3   1     3
4   3     2
<bound method NDFrame.head of 0       0
1       0
2       0
3       0
4       0
       ..
1020    1
1021    0
1022    0
1023    1
1024    0
Name: target, Length: 1025, dtype: int64>

In [13]:
#train-test

X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

#Train Random Forest with Different Numbers of Trees

In [16]:
trees = [10,50,100,200]

results = []

for n in trees:

  model = RandomForestClassifier(
    n_estimators=n,
    random_state=42
  )


  start = time.time()

  model.fit(X_train,y_train)

  end = time.time()

  train_acc = model.score(X_train,y_train)
  test_acc = model.score(X_test,y_test)



  training_time = end -start

  results.append([
      n,
      round(train_acc,4),
      round(test_acc, 4),
      round(training_time,4)
  ])

In [17]:
#Comparison Table

comparison = pd.DataFrame(
    results,
    columns=[
        "Number of Trees",
        "Train Accuracy",
        "Test Accuracy",
        "Training Time (sec)"
    ]
)

comparison

   Number of Trees  Train Accuracy  Test Accuracy  Training Time (sec)
0               10             1.0            1.0               0.0411
1               50             1.0            1.0               0.2034
2              100             1.0            1.0               0.3840
3              200             1.0            1.0               0.8775

In [20]:
# Best Number of Trees

best = comparison.loc[
    comparison["Test Accuracy"].idxmax()
]

print(best)

Number of Trees        10.0000
Train Accuracy          1.0000
Test Accuracy           1.0000
Training Time (sec)     0.0411
Name: 0, dtype: float64

In [21]:
print("========== Comparison ==========\n")

print(comparison)

print("\n========== Best Result ==========\n")

print(best)

========== Comparison ==========

   Number of Trees  Train Accuracy  Test Accuracy  Training Time (sec)
0               10             1.0            1.0               0.0411
1               50             1.0            1.0               0.2034
2              100             1.0            1.0               0.3840
3              200             1.0            1.0               0.8775

========== Best Result ==========

Number of Trees        10.0000
Train Accuracy          1.0000
Test Accuracy           1.0000
Training Time (sec)     0.0411
Name: 0, dtype: float64

Which number of trees gives the best balance between performance and computation?



Increasing the number of trees generally improves the stability and accuracy of the Random Forest model, but it also increases the training time. In this experiment, 100 trees provided the best balance between prediction performance and computational cost. Increasing the number of trees from 100 to 200 resulted in little or no improvement in test accuracy while requiring more training time. Therefore, 100 trees is the most efficient choice for this dataset.