5. Understanding Bias-Variance Tradeoff

Dataset: Titanic Dataset
Download:

https://www.kaggle.com/competitions/titanic/data

Tasks

Train the following models:
Decision Tree (depth=2)

Decision Tree (depth=10)

Random Forest (100 trees)

Compare:

Training Accuracy

Testing Accuracy

For each model determine:
High Bias?

High Variance?

Balanced?

Explain your reasoning.

In [8]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [9]:
df = pd.read_csv("titanic_data_updated.csv")

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,no,third,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,yes,first,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,yes,third,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,yes,first,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,no,third,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [10]:
#Select Features

df = df[['Pclass','Sex','Age','SibSp','Parch','Fare','Embarked','Survived']]

In [11]:
#Handle Missing Values

df['Age'] = df['Age'].fillna(df['Age'].median())
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

In [12]:
# Convert Catergorial Data

df = pd.get_dummies(df, drop_first=True)

df.head()

,Age,SibSp,Parch,Fare,Pclass_second,Pclass_third,Sex_male,Embarked_Q,Embarked_S,Survived_yes
0,22.0,1,0,7.2500,False,True,True,False,True,False
1,38.0,1,0,71.2833,False,False,False,False,False,True
2,26.0,0,0,7.9250,False,True,False,False,True,True
3,35.0,1,0,53.1000,False,False,False,False,True,True
4,35.0,0,0,8.0500,False,True,True,False,True,False

In [14]:
X = df.drop("Survived_yes", axis=1)
y = df["Survived_yes"]

In [15]:
# Train - test
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [16]:
# Train Modles

model1 = DecisionTreeClassifier(max_depth=2, random_state=42)

model2 = DecisionTreeClassifier(max_depth=10, random_state=42)

model3 = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

model1.fit(X_train, y_train)
model2.fit(X_train, y_train)
model3.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [17]:
# Calculate Training & Testing Accuracy

models = {
    "Decision Tree (Depth=2)": model1,
    "Decision Tree (Depth=10)": model2,
    "Random Forest (100 Trees)": model3
}

results = []

for name, model in models.items():

    train_acc = model.score(X_train, y_train)

    test_acc = model.score(X_test, y_test)

    results.append([
        name,
        round(train_acc,4),
        round(test_acc,4)
    ])

comparison = pd.DataFrame(
    results,
    columns=[
        "Model",
        "Training Accuracy",
        "Testing Accuracy"
    ]
)

comparison

                       Model  Training Accuracy  Testing Accuracy
0    Decision Tree (Depth=2)             0.8034            0.7654
1   Decision Tree (Depth=10)             0.9157            0.7821
2  Random Forest (100 Trees)             0.9789            0.7989

In [18]:
# Determine Bias & Variance

comparison["Difference"] = (
    comparison["Training Accuracy"]
    - comparison["Testing Accuracy"]
).round(4)

status = []

for i in range(len(comparison)):

    train = comparison.loc[i,"Training Accuracy"]
    test = comparison.loc[i,"Testing Accuracy"]
    diff = train - test

    if train < 0.85:
        status.append("High Bias")

    elif diff > 0.10:
        status.append("High Variance")

    else:
        status.append("Balanced")

comparison["Conclusion"] = status

comparison

,Model,Training Accuracy,Testing Accuracy,Difference,Conclusion
0,Decision Tree (Depth=2),0.8034,0.7654,0.0380,High Bias
1,Decision Tree (Depth=10),0.9157,0.7821,0.1336,High Variance
2,Random Forest (100 Trees),0.9789,0.7989,0.1800,High Variance

In [19]:
for i in range(len(comparison)):

    print("="*50)

    print("Model :", comparison.loc[i,"Model"])

    print("Training Accuracy :", comparison.loc[i,"Training Accuracy"])

    print("Testing Accuracy  :", comparison.loc[i,"Testing Accuracy"])

    print("Conclusion :", comparison.loc[i,"Conclusion"])

    print()

==================================================
Model : Decision Tree (Depth=2)
Training Accuracy : 0.8034
Testing Accuracy  : 0.7654
Conclusion : High Bias

==================================================
Model : Decision Tree (Depth=10)
Training Accuracy : 0.9157
Testing Accuracy  : 0.7821
Conclusion : High Variance

==================================================
Model : Random Forest (100 Trees)
Training Accuracy : 0.9789
Testing Accuracy  : 0.7989
Conclusion : High Variance

Training Accuracy ≈ Testing Accuracy
        and both low
        → High Bias

Training Accuracy >> Testing Accuracy
        → High Variance

Training Accuracy ≈ Testing Accuracy
        and both high
        → Balanced