In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

In [3]:
df = pd.read_csv("employee_turnover.csv")

df.head()

,Job_Satisfaction,Performance_Rating,Years_At_Company,Work_Life_Balance,Distance_From_Home,Monthly_Income,Education_Level,Age,Num_Companies_Worked,Employee_Role,Annual_Bonus,Training_Hours,Department,Annual_Bonus_Squared,Annual_Bonus_Training_Hours_Interaction,Employee_Turnover
0,0.562326,0.141129,0.123989,0.347583,0.330353,0.328853,0.600933,0.315990,0.768736,0.090671,0.324786,0.669193,0.602932,0.105486,0.217344,0
1,0.017041,0.559047,0.511203,0.793908,0.423550,0.553450,0.742009,0.897146,0.380035,0.601633,0.694611,0.043271,0.800761,0.482484,0.030056,0
2,0.774699,0.604371,0.798174,0.260500,0.804034,0.131800,0.775178,0.830947,0.218726,0.972936,0.153476,0.701336,0.705275,0.023555,0.107638,1
3,0.628174,0.385249,0.230104,0.516809,0.272248,0.589249,0.482409,0.090507,0.402746,0.132842,0.305973,0.549688,0.600531,0.093620,0.168190,0
4,0.799183,0.199967,0.839029,0.247927,0.341934,0.076818,0.055356,0.680860,0.923341,0.493017,0.844094,0.793751,0.664679,0.712494,0.670000,0

In [7]:
print(df.shape)
print(df.info())

(1350, 16)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1350 entries, 0 to 1349
Data columns (total 16 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Job_Satisfaction                         1350 non-null   float64
 1   Performance_Rating                       1350 non-null   float64
 2   Years_At_Company                         1350 non-null   float64
 3   Work_Life_Balance                        1350 non-null   float64
 4   Distance_From_Home                       1350 non-null   float64
 5   Monthly_Income                           1350 non-null   float64
 6   Education_Level                          1350 non-null   float64
 7   Age                                      1350 non-null   float64
 8   Num_Companies_Worked                     1350 non-null   float64
 9   Employee_Role                            1350 non-null   float64
 10  Annual_Bonus                             1350 non-null   float64
 11  Training_Hours                           1350 non-null   float64
 12  Department                               1350 non-null   float64
 13  Annual_Bonus_Squared                     1350 non-null   float64
 14  Annual_Bonus_Training_Hours_Interaction  1350 non-null   float64
 15  Employee_Turnover                        1350 non-null   int64
dtypes: float64(15), int64(1)
memory usage: 168.9 KB
None

In [8]:
df.isnull().sum()

Job_Satisfaction                           0
Performance_Rating                         0
Years_At_Company                           0
Work_Life_Balance                          0
Distance_From_Home                         0
Monthly_Income                             0
Education_Level                            0
Age                                        0
Num_Companies_Worked                       0
Employee_Role                              0
Annual_Bonus                               0
Training_Hours                             0
Department                                 0
Annual_Bonus_Squared                       0
Annual_Bonus_Training_Hours_Interaction    0
Employee_Turnover                          0
dtype: int64

In [9]:
X = df.drop("Employee_Turnover",axis = 1)
y = df["Employee_Turnover"]

In [10]:
X_train,X_test,y_train,y_test, = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [11]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [12]:
baseline_model = LogisticRegression(random_state=42)

baseline_model.fit(X_train_scaled, y_train)

baseline_pred = baseline_model.predict(X_test_scaled)

In [13]:
print("Accuracy :", accuracy_score(y_test, baseline_pred))
print("Precision:", precision_score(y_test, baseline_pred))
print("Recall   :", recall_score(y_test, baseline_pred))
print("F1 Score :", f1_score(y_test, baseline_pred))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, baseline_pred))

print("\nClassification Report")
print(classification_report(y_test, baseline_pred))

Accuracy : 0.8814814814814815
Precision: 0.8923076923076924
Recall   : 0.8656716417910447
F1 Score : 0.8787878787878788

Confusion Matrix
[[122  14]
 [ 18 116]]

Classification Report
              precision    recall  f1-score   support

           0       0.87      0.90      0.88       136
           1       0.89      0.87      0.88       134

    accuracy                           0.88       270
   macro avg       0.88      0.88      0.88       270
weighted avg       0.88      0.88      0.88       270

In [14]:
l1_model = LogisticRegression(
    penalty='l1',
    solver='liblinear',
    random_state=42
)

l1_model.fit(X_train_scaled, y_train)

l1_pred = l1_model.predict(X_test_scaled)

In [15]:
print("Accuracy :", accuracy_score(y_test, l1_pred))
print("Precision:", precision_score(y_test, l1_pred))
print("Recall   :", recall_score(y_test, l1_pred))
print("F1 Score :", f1_score(y_test, l1_pred))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, l1_pred))

print("\nClassification Report")
print(classification_report(y_test, l1_pred))

Accuracy : 0.8814814814814815
Precision: 0.8923076923076924
Recall   : 0.8656716417910447
F1 Score : 0.8787878787878788

Confusion Matrix
[[122  14]
 [ 18 116]]

Classification Report
              precision    recall  f1-score   support

           0       0.87      0.90      0.88       136
           1       0.89      0.87      0.88       134

    accuracy                           0.88       270
   macro avg       0.88      0.88      0.88       270
weighted avg       0.88      0.88      0.88       270

In [16]:
l2_model = LogisticRegression(
    penalty='l2',
    solver='lbfgs',
    random_state=42
)

l2_model.fit(X_train_scaled, y_train)

l2_pred = l2_model.predict(X_test_scaled)

In [17]:
print("Accuracy :", accuracy_score(y_test, l2_pred))
print("Precision:", precision_score(y_test, l2_pred))
print("Recall   :", recall_score(y_test, l2_pred))
print("F1 Score :", f1_score(y_test, l2_pred))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, l2_pred))

print("\nClassification Report")
print(classification_report(y_test, l2_pred))

Accuracy : 0.8814814814814815
Precision: 0.8923076923076924
Recall   : 0.8656716417910447
F1 Score : 0.8787878787878788

Confusion Matrix
[[122  14]
 [ 18 116]]

Classification Report
              precision    recall  f1-score   support

           0       0.87      0.90      0.88       136
           1       0.89      0.87      0.88       134

    accuracy                           0.88       270
   macro avg       0.88      0.88      0.88       270
weighted avg       0.88      0.88      0.88       270

In [18]:
results = pd.DataFrame({
    "Model": [
        "Baseline Logistic Regression",
        "Logistic Regression (L1)",
        "Logistic Regression (L2)"
    ],
    "Accuracy": [
        accuracy_score(y_test, baseline_pred),
        accuracy_score(y_test, l1_pred),
        accuracy_score(y_test, l2_pred)
    ],
    "Precision": [
        precision_score(y_test, baseline_pred),
        precision_score(y_test, l1_pred),
        precision_score(y_test, l2_pred)
    ],
    "Recall": [
        recall_score(y_test, baseline_pred),
        recall_score(y_test, l1_pred),
        recall_score(y_test, l2_pred)
    ],
    "F1 Score": [
        f1_score(y_test, baseline_pred),
        f1_score(y_test, l1_pred),
        f1_score(y_test, l2_pred)
    ]
})

results

                          Model  Accuracy  Precision    Recall  F1 Score
0  Baseline Logistic Regression  0.881481   0.892308  0.865672  0.878788
1      Logistic Regression (L1)  0.881481   0.892308  0.865672  0.878788
2      Logistic Regression (L2)  0.881481   0.892308  0.865672  0.878788

In [19]:
best_model = results.loc[results["Accuracy"].idxmax()]

print("Best Model:")
print(best_model)

Best Model:
Model        Baseline Logistic Regression
Accuracy                         0.881481
Precision                        0.892308
Recall                           0.865672
F1 Score                         0.878788
Name: 0, dtype: object